services:
  # Screenshot Service for Development
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: screenshot-service-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./scripts:/usr/src/app/scripts
      - ./logs:/usr/src/app/logs
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh:ro
      - /usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
    networks:
      - screenshot-network
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: ['/bin/sh', '/usr/src/app/docker-entrypoint.sh']
    command: yarn dev

  # LocalStack for local AWS development
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_screenshot_service
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-init:/docker-entrypoint-initaws.d
    networks:
      - screenshot-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  screenshot-network:
    driver: bridge

volumes:
  localstack-data:
